# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.31

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /opt/homebrew/bin/cmake

# The command to remove a file.
RM = /opt/homebrew/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /Users/lukasmolzberger/CLionProjects/aika-cpp

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /Users/lukasmolzberger/CLionProjects/aika-cpp

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake cache editor..."
	/opt/homebrew/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	/opt/homebrew/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/lukasmolzberger/CLionProjects/aika-cpp/CMakeFiles /Users/lukasmolzberger/CLionProjects/aika-cpp//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/lukasmolzberger/CLionProjects/aika-cpp/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named aika

# Build rule for target.
aika: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 aika
.PHONY : aika

# fast build rule for target.
aika/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/aika.dir/build.make CMakeFiles/aika.dir/build
.PHONY : aika/fast

#=============================================================================
# Target rules for targets named pybind11_headers

# Build rule for target.
pybind11_headers: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 pybind11_headers
.PHONY : pybind11_headers

# fast build rule for target.
pybind11_headers/fast:
	$(MAKE) $(MAKESILENT) -f pybind11/CMakeFiles/pybind11_headers.dir/build.make pybind11/CMakeFiles/pybind11_headers.dir/build
.PHONY : pybind11_headers/fast

src/fields/field.o: src/fields/field.cpp.o
.PHONY : src/fields/field.o

# target to build an object file
src/fields/field.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/aika.dir/build.make CMakeFiles/aika.dir/src/fields/field.cpp.o
.PHONY : src/fields/field.cpp.o

src/fields/field.i: src/fields/field.cpp.i
.PHONY : src/fields/field.i

# target to preprocess a source file
src/fields/field.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/aika.dir/build.make CMakeFiles/aika.dir/src/fields/field.cpp.i
.PHONY : src/fields/field.cpp.i

src/fields/field.s: src/fields/field.cpp.s
.PHONY : src/fields/field.s

# target to generate assembly for a file
src/fields/field.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/aika.dir/build.make CMakeFiles/aika.dir/src/fields/field.cpp.s
.PHONY : src/fields/field.cpp.s

src/fields/field_definition.o: src/fields/field_definition.cpp.o
.PHONY : src/fields/field_definition.o

# target to build an object file
src/fields/field_definition.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/aika.dir/build.make CMakeFiles/aika.dir/src/fields/field_definition.cpp.o
.PHONY : src/fields/field_definition.cpp.o

src/fields/field_definition.i: src/fields/field_definition.cpp.i
.PHONY : src/fields/field_definition.i

# target to preprocess a source file
src/fields/field_definition.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/aika.dir/build.make CMakeFiles/aika.dir/src/fields/field_definition.cpp.i
.PHONY : src/fields/field_definition.cpp.i

src/fields/field_definition.s: src/fields/field_definition.cpp.s
.PHONY : src/fields/field_definition.s

# target to generate assembly for a file
src/fields/field_definition.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/aika.dir/build.make CMakeFiles/aika.dir/src/fields/field_definition.cpp.s
.PHONY : src/fields/field_definition.cpp.s

src/fields/type.o: src/fields/type.cpp.o
.PHONY : src/fields/type.o

# target to build an object file
src/fields/type.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/aika.dir/build.make CMakeFiles/aika.dir/src/fields/type.cpp.o
.PHONY : src/fields/type.cpp.o

src/fields/type.i: src/fields/type.cpp.i
.PHONY : src/fields/type.i

# target to preprocess a source file
src/fields/type.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/aika.dir/build.make CMakeFiles/aika.dir/src/fields/type.cpp.i
.PHONY : src/fields/type.cpp.i

src/fields/type.s: src/fields/type.cpp.s
.PHONY : src/fields/type.s

# target to generate assembly for a file
src/fields/type.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/aika.dir/build.make CMakeFiles/aika.dir/src/fields/type.cpp.s
.PHONY : src/fields/type.cpp.s

src/fields/type_registry.o: src/fields/type_registry.cpp.o
.PHONY : src/fields/type_registry.o

# target to build an object file
src/fields/type_registry.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/aika.dir/build.make CMakeFiles/aika.dir/src/fields/type_registry.cpp.o
.PHONY : src/fields/type_registry.cpp.o

src/fields/type_registry.i: src/fields/type_registry.cpp.i
.PHONY : src/fields/type_registry.i

# target to preprocess a source file
src/fields/type_registry.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/aika.dir/build.make CMakeFiles/aika.dir/src/fields/type_registry.cpp.i
.PHONY : src/fields/type_registry.cpp.i

src/fields/type_registry.s: src/fields/type_registry.cpp.s
.PHONY : src/fields/type_registry.s

# target to generate assembly for a file
src/fields/type_registry.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/aika.dir/build.make CMakeFiles/aika.dir/src/fields/type_registry.cpp.s
.PHONY : src/fields/type_registry.cpp.s

src/fields/type_registry_python.o: src/fields/type_registry_python.cpp.o
.PHONY : src/fields/type_registry_python.o

# target to build an object file
src/fields/type_registry_python.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/aika.dir/build.make CMakeFiles/aika.dir/src/fields/type_registry_python.cpp.o
.PHONY : src/fields/type_registry_python.cpp.o

src/fields/type_registry_python.i: src/fields/type_registry_python.cpp.i
.PHONY : src/fields/type_registry_python.i

# target to preprocess a source file
src/fields/type_registry_python.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/aika.dir/build.make CMakeFiles/aika.dir/src/fields/type_registry_python.cpp.i
.PHONY : src/fields/type_registry_python.cpp.i

src/fields/type_registry_python.s: src/fields/type_registry_python.cpp.s
.PHONY : src/fields/type_registry_python.s

# target to generate assembly for a file
src/fields/type_registry_python.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/aika.dir/build.make CMakeFiles/aika.dir/src/fields/type_registry_python.cpp.s
.PHONY : src/fields/type_registry_python.cpp.s

src/network/model.o: src/network/model.cpp.o
.PHONY : src/network/model.o

# target to build an object file
src/network/model.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/aika.dir/build.make CMakeFiles/aika.dir/src/network/model.cpp.o
.PHONY : src/network/model.cpp.o

src/network/model.i: src/network/model.cpp.i
.PHONY : src/network/model.i

# target to preprocess a source file
src/network/model.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/aika.dir/build.make CMakeFiles/aika.dir/src/network/model.cpp.i
.PHONY : src/network/model.cpp.i

src/network/model.s: src/network/model.cpp.s
.PHONY : src/network/model.s

# target to generate assembly for a file
src/network/model.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/aika.dir/build.make CMakeFiles/aika.dir/src/network/model.cpp.s
.PHONY : src/network/model.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... aika"
	@echo "... pybind11_headers"
	@echo "... src/fields/field.o"
	@echo "... src/fields/field.i"
	@echo "... src/fields/field.s"
	@echo "... src/fields/field_definition.o"
	@echo "... src/fields/field_definition.i"
	@echo "... src/fields/field_definition.s"
	@echo "... src/fields/type.o"
	@echo "... src/fields/type.i"
	@echo "... src/fields/type.s"
	@echo "... src/fields/type_registry.o"
	@echo "... src/fields/type_registry.i"
	@echo "... src/fields/type_registry.s"
	@echo "... src/fields/type_registry_python.o"
	@echo "... src/fields/type_registry_python.i"
	@echo "... src/fields/type_registry_python.s"
	@echo "... src/network/model.o"
	@echo "... src/network/model.i"
	@echo "... src/network/model.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

